main:
  - name: Main
    url: /en/
    weight: 10
  - name: Posts
    url: /en/post/
    weight: 20
  - name: Projects
    url: /en/project/
    weight: 30
  - name: Gallery
    url: /en/gallery/
    weight: 35
  - name: Music
    identifier: music
    url: /en/music/
    weight: 40
  - name: BEATS
    url: /en/music/beats/
    weight: 41
    parent: music
  - name: LOOPS
    url: /en/music/loops/
    weight: 42
    parent: music
  - name: Contact
    url: /en/contact/
    weight: 60