name = "BIGXEUNG's Workshop"
license = "MIT"
licenselink = "https://github.com/bigxeung/bigxeung.github.io/blob/develop/LICENSE.md"
description = "BIGXEUNG's Workshop is a personal website for music production and software development. It features a stunning homepage, music, projects, posts, and a contact form."
homepage = "https://github.com/bigxeung/bigxeung.github.io"
tags = ["academic",
        "university",
        "research",
        "publications",
        "widgets",
        "portfolio",
        "responsive",
        "clean",
        "company",
        "blog",
        "events",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "landing page",
        "contact form",
        "mobile",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "slide"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "BIGXEUNG"
  homepage = "https://bigxeung.github.io"
